name: Build and Release

on:
  push:
    tags:
      - 'v*' # Dispara quando uma tag que começa com "v" é enviada (ex: v1.0.0)

jobs:
  release:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      # No macOS e Windows, a dependência do yt-dlp não possui permissão de execução,
      # vamos dar permissão de execução (Linux/macOS)
      - name: Set yt-dlp permissions (Unix)
        if: matrix.os != 'windows-latest'
        run: chmod +x bin/yt-dlp

      - name: Build & Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist -- -p always
